version: "3.9"

services:

  redis:
    networks:
      - main
    image: redis:latest
    container_name: redis-db
    command: bash -c "redis-server --appendonly yes "
    ports: 
      - "6379:6379"
    volumes:
      - "redis-db-storage:/data"

  flask:
    networks:
      - main
    build: ./api
    image: flask-api:latest
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    env_file:
    - ${API_CONFIG}  # Path to API Server config data (.env)

  splash:
    networks:
      - main
    image: scrapinghub/splash
    container_name: splash
    ports:
      - "8050:8050"

  streamlit:
    networks:
      - main
    build: ./frontend
    image: streamlit-frontend
    container_name: streamlit-frontend
    ports:
      - "9000:9000"
    depends_on:
      - flask
    environment:
    - API_SERVER=flask-api
    - API_SERVER_PORT=5000

  mongo:
    networks:
      - main
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - "mongo-db-storage:/data/db"
    env_file:
      - ${MONGO_CONFIG}   # Path to MongoDB config data (.env file)

    
volumes:
  redis-db-storage:
  mongo-db-storage:


networks:
  main:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1