apiVersion: v1
kind: Pod
metadata:
  name: scraper-pod
  namespace: job-collector-ns
  labels:
    app: scraper
spec:
  containers:
  - name: scraper
    image: dawrr756hj23/joffc:scraper
    envFrom:
    - configMapRef:
        name: scraper-configmap
    - secretRef:
        name: mongo-secret