apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: job-collector-ns
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    nodePort: 30045
    port: 80
    targetPort: 8501