apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: job-collector-ns
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    nodePort: 32144
    port: 8501
    targetPort: 8501