apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: job-collector-ns
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 5000
    targetPort: 5000