apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: job-collector-ns
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501