apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: ""
  claimRef:
    name: mongo-pvc
    namespace: job-collector-ns
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    secretNamespace: job-collector-ns
    shareName: mongo-job-offer-collector